# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    # Common setup (includes setup for C/C++)
    apt-get update
    apt-get upgrade -y
    apt-get install -y make
    apt-get install -y emacs
    apt-get install -y nasm
    apt-get install -y curl
    apt-get install -y build-essential
    apt-get install -y libssl-dev
    apt-get install -y pkg-config
    chown -R vagrant:vagrant /vagrant
    echo "export PATH=/home/vagrant/.local/bin:$PATH >> /home/vagrant/.profile"

    # OCaml
    apt-get install -y apt-utils
    apt-get install -y m4
    apt-get install -y software-properties-common
    add-apt-repository -y ppa:avsm/ppa
    apt install -y opam

    # Rust
    apt-get install -y --no-install-recommends \
        ca-certificates \
        gcc \
        libc6-dev \
        ; \
    echo "export RUSTUP_HOME=/usr/local/rustup" >> /home/vagrant/.profile
    echo "export CARGO_HOME=/usr/local/cargo" >> /home/vagrant/.profile
    echo "export PATH=/usr/local/cargo/bin:$PATH" >> /home/vagrant/.profile
    source /home/vagrant/.profile
    env
    curl https://sh.rustup.rs -sSf | bash -s -- -y

    rustup --version
    cargo --version
    rustc --version

    chmod -R a+w $RUSTUP_HOME $CARGO_HOME;

    # Haskell
    curl -sSL https://get.haskellstack.org/ | sh -s

    # Java
    apt-get install -y default-jdk

  SHELL

  # Rust setup in user mode
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    cargo install cargo-prefetch
    cargo prefetch
    cargo install lalrpop
  SHELL

  # OCaml setup in user mode
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    opam init -y
    opam install -y ocamlbuild
    opam install -y menhir

    echo "test -r /home/vagrant/.opam/opam-init/init.sh && . /home/vagrant/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true" >> /home/vagrant/.profile
  SHELL

  # Haskell setup in user mode
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    stack setup --resolver lts-18.14
    stack install --resolver lts-18.14 unordered-containers pretty-show prettyprinter optparse-applicative uniplate protolude recursion-schemes
  SHELL

end
